services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  authservice1:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5232:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=secret

  authservice2:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5233:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=secret

  chatservice1:
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    ports:
      - "5115:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chatdb;Username=postgres;Password=secret

  chatservice2:
    build:
      context: ./ChatService
      dockerfile: Dockerfile
    ports:
      - "5116:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=chatdb;Username=postgres;Password=secret

  fileservice1:
    build:
      context: ./FileService
      dockerfile: Dockerfile
    ports:
      - "5277:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=filedb;Username=postgres;Password=secret
    volumes:
      - ./data:/app/data

  fileservice2:
    build:
      context: ./FileService
      dockerfile: Dockerfile
    ports:
      - "5278:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=filedb;Username=postgres;Password=secret
    volumes:
      - ./data:/app/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authservice1
      - authservice2
      - chatservice1
      - chatservice2
      - fileservice1
      - fileservice2

volumes:
  postgres_data:
  pgadmin_data:
